"""Least-privilege runtime DB users (SEC-1), regenerated by ``setup:upgrade``, which alone
connects as the migration user. The backend (cron, web) gets DML on every table; the toolbox
gets exactly what its SQL does. Each run syncs passwords, revokes all, grants again (MySQL 8).
"""
from __future__ import annotations

MIGRATE_USER = "cron_agent"
TOOLBOX_USER = "agento_toolbox"

# Every table the toolbox SQL touches; deny by default. UPDATE/DELETE ... WHERE needs SELECT;
# INSERT ... ON DUPLICATE KEY UPDATE needs UPDATE.
TOOLBOX_GRANTS = {
    "agent_view": "SELECT",
    "core_config_data": "SELECT",
    "launch": "SELECT",
    "role_grant": "SELECT",
    "session": "SELECT",
    "user": "SELECT",
    "workspace": "SELECT",
    "job": "SELECT, INSERT",
    "miniapp_activation": "SELECT, INSERT, UPDATE, DELETE",
    "versioned_artifact": "SELECT, INSERT, UPDATE, DELETE",
    "versioned_artifact_audit": "INSERT",
    "tool_invocation": "SELECT, INSERT, UPDATE",
    "toolbox_capability": "SELECT, UPDATE",
}


def apply_grants(conn, *, backend_user: str, backend_password: str, toolbox_password: str) -> None:
    """Create or sync both runtime users and regenerate their grants. Fail closed (SEC-9)."""
    if not backend_password or not toolbox_password:
        raise ValueError("MYSQL_PASSWORD and MYSQL_TOOLBOX_PASSWORD must be set (run 'agento upgrade')")
    if backend_user in ("", MIGRATE_USER, TOOLBOX_USER):
        raise ValueError(f"MYSQL_USER must be the backend user, not {backend_user!r}")
    with conn.cursor() as cur:
        cur.execute("SELECT table_name AS table_name FROM information_schema.tables "
                    "WHERE table_schema = DATABASE()")
        tables = [row["table_name"] for row in cur.fetchall()]
        # A table-level GRANT needs the table to exist: a disabled module may not have made it.
        toolbox = [f"GRANT {TOOLBOX_GRANTS[t]} ON `{t}` TO %s@'%%'" for t in tables if t in TOOLBOX_GRANTS]
        for user, password, grants in (
            (backend_user, backend_password, ["GRANT SELECT, INSERT, UPDATE, DELETE ON * TO %s@'%%'"]),
            (TOOLBOX_USER, toolbox_password, toolbox),
        ):
            cur.execute("CREATE USER IF NOT EXISTS %s@'%%' IDENTIFIED BY %s", (user, password))
            cur.execute("ALTER USER %s@'%%' IDENTIFIED BY %s", (user, password))
            # ponytail: a sub-ms window with no grant for a live caller; per-table
            # REVOKE IF EXISTS of only the extra privileges closes it, if it ever bites.
            cur.execute("REVOKE ALL PRIVILEGES, GRANT OPTION FROM %s@'%%'", (user,))
            for sql in grants:
                cur.execute(sql, (user,))
    conn.commit()
