// Collects the core modules' panel screens (PRD E8 §7) into src/generated/registry.ts.
// Only src/agento/modules/ is scanned: a user (app/code) or PyPI module never ships panel
// JavaScript into the origin that holds the session cookie.
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { assertPanelModule } from "../../packages/api/src/contract.ts";

const PANEL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const MODULES_DIR = resolve(PANEL, "../../src/agento/modules");
const OUT = join(PANEL, "src/generated/registry.ts");

export async function collect(modulesDir = MODULES_DIR): Promise<string[]> {
  const found: string[] = [];
  for (const dir of readdirSync(modulesDir).sort()) {
    const entry = join(modulesDir, dir, "panel", "index.ts");
    if (!existsSync(entry)) continue;
    const mod = await import(pathToFileURL(entry).href);
    assertPanelModule(dir, mod.default);
    found.push(dir);
  }
  return found;
}

export function render(dirs: string[], modulesDir = MODULES_DIR): string {
  const rel = (d: string) => relative(dirname(OUT), join(modulesDir, d, "panel", "index.ts")).split("\\").join("/");
  return [
    "// Generated by panel/scripts/gen-registry.ts; do not edit.",
    'import { assertPanelModule, type PanelModule } from "@agento/api";',
    ...dirs.map((d, i) => `import m${i} from "${rel(d)}";`),
    "",
    "export const MODULES: PanelModule[] = [",
    ...dirs.map((d, i) => `  assertPanelModule(${JSON.stringify(d)}, m${i}),`),
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const dirs = await collect();
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, render(dirs));
}
