// Builds the miniapp kit (PRD E8 §10): `agento-ui.css` from the tokens and the component
// rules, the custom elements, the bridge client (a byte copy of the E6 SDK) and the font.
// Output: src/agento/framework/web/miniapp-ui/<version>/, served by proxy at /_ui/<version>/.
//
// A version is immutable once released (its URL is cached as `immutable`): a released
// version's files are committed under `released/<version>/`, every released version is
// copied through unchanged, and a build whose current output differs from its released
// bytes fails. `--release` writes the current build as the released copy.
import { copyFileSync, cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { variablesCss } from "../src/tokens.ts";

const KIT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = resolve(KIT, "../../..");
export const OUT = join(REPO, "src/agento/framework/web/miniapp-ui");
export const SDK = join(REPO, "src/agento/modules/miniapps/sdk/agento-sdk.js");
const FONTS = join(KIT, "../../node_modules/@fontsource/inter");
const WEIGHTS = [400, 500, 600];

export const KIT_VERSION: string = JSON.parse(readFileSync(join(KIT, "package.json"), "utf8")).version;

export function kitCss(): string {
  const faces = WEIGHTS.map((w) =>
    `@font-face {\n  font-family: Inter;\n  font-style: normal;\n  font-weight: ${w};\n  font-display: swap;\n`
    + `  src: url("./fonts/inter-latin-${w}-normal.woff2") format("woff2");\n}`).join("\n");
  return [
    `/* agento-ui ${KIT_VERSION} — generated by frontend/packages/miniapp-kit; do not edit. */`,
    faces,
    variablesCss(),
    readFileSync(join(KIT, "src/components.css"), "utf8"),
  ].join("\n\n");
}

function buildInto(dir: string): void {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(join(dir, "fonts"), { recursive: true });
  writeFileSync(join(dir, "agento-ui.css"), kitCss());
  copyFileSync(join(KIT, "src/agento-ui.js"), join(dir, "agento-ui.js"));
  copyFileSync(SDK, join(dir, "agento-bridge.js"));
  for (const w of WEIGHTS) {
    const name = `inter-latin-${w}-normal.woff2`;
    copyFileSync(join(FONTS, "files", name), join(dir, "fonts", name));
  }
  copyFileSync(join(FONTS, "LICENSE"), join(dir, "fonts", "LICENSE"));
}

function files(dir: string, base = dir): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? files(join(dir, e.name), base) : [join(dir, e.name).slice(base.length + 1)]).sort();
}

/** The paths whose bytes differ between two built versions (empty = identical). */
export function diffDirs(a: string, b: string): string[] {
  const fa = files(a);
  const fb = files(b);
  const all = [...new Set([...fa, ...fb])].sort();
  return all.filter((f) => !fa.includes(f) || !fb.includes(f)
    || !readFileSync(join(a, f)).equals(readFileSync(join(b, f))));
}

export function main(argv: string[]): void {
  const released = join(KIT, "released");
  const current = join(KIT, "dist", KIT_VERSION);
  buildInto(current);
  const frozen = join(released, KIT_VERSION);
  if (argv.includes("--release")) {
    if (existsSync(frozen)) throw new Error(`kit ${KIT_VERSION} is already released; bump the kit version`);
    cpSync(current, frozen, { recursive: true });
  } else if (existsSync(frozen)) {
    const changed = diffDirs(frozen, current);
    if (changed.length) {
      throw new Error(`kit ${KIT_VERSION} is released and immutable, but these files changed: `
        + `${changed.join(", ")}. Bump "version" in packages/miniapp-kit/package.json.`);
    }
  }
  // Empty OUT, never remove it: proxy bind-mounts this directory, and a re-created directory
  // is a new inode the running container does not see.
  mkdirSync(OUT, { recursive: true });
  for (const n of readdirSync(OUT)) rmSync(join(OUT, n), { recursive: true, force: true });
  for (const v of existsSync(released) ? readdirSync(released) : []) cpSync(join(released, v), join(OUT, v), { recursive: true });
  cpSync(current, join(OUT, KIT_VERSION), { recursive: true });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main(process.argv.slice(2));
