"""Tests for jira_periodic_tasks observers (AG-56 crontab restore on setup)."""
from __future__ import annotations

import logging
from dataclasses import dataclass
from unittest.mock import MagicMock, patch

import pytest

from agento.modules.jira_periodic_tasks.src.crontab import MARKER_BEGIN, MARKER_END
from agento.modules.jira_periodic_tasks.src.observers import (
    RestoreCrontabOnSetupObserver,
    _reverse_frequency_map,
)


@dataclass
class FakeSetupCompleteEvent:
    dry_run: bool = False


FREQ_MAP = {
    "Every 5min": "*/5 * * * *",
    "Daily at 8:00": "0 8 * * *",
}


def _conn_returning(rows):
    """Build a mock pymysql DictCursor connection yielding ``rows``."""
    cur = MagicMock()
    cur.fetchall.return_value = rows
    conn = MagicMock()
    conn.cursor.return_value.__enter__.return_value = cur
    return conn


def _run_observer(rows, current_crontab, *, freq_map=FREQ_MAP):
    """Execute the observer with a real CrontabManager over a faked ``crontab``.

    Returns (written_crontab_or_None, caplog_records) — ``written`` is the text
    handed to ``crontab -`` or None if the crontab was left unchanged.
    """
    written: dict[str, str] = {}

    def fake_run(cmd, *args, **kwargs):
        if cmd == ["crontab", "-l"]:
            return MagicMock(returncode=0, stdout=current_crontab)
        if cmd == ["crontab", "-"]:
            written["value"] = kwargs["input"]
            return MagicMock(returncode=0)
        raise AssertionError(f"unexpected command {cmd}")

    cfg = MagicMock()
    cfg.frequency_map = freq_map

    with patch(
        "agento.modules.jira_periodic_tasks.src.crontab.subprocess.run",
        side_effect=fake_run,
    ), patch(
        "agento.framework.bootstrap.get_module_config", return_value=cfg
    ), patch(
        "agento.framework.database_config.DatabaseConfig.from_env"
    ), patch(
        "agento.framework.db.get_connection", return_value=_conn_returning(rows)
    ), patch(
        "agento.framework.lock.FileLock"
    ):
        observer = RestoreCrontabOnSetupObserver()
        observer.execute(FakeSetupCompleteEvent(dry_run=False))

    return written.get("value")


# Real AGENTO markers live in framework.crontab; reproduce the literal here so the
# test does not couple to that module's constant.
AGENTO_BEGIN = "# AGENTO:BEGIN - Auto-generated by setup:upgrade. Do not edit manually."
AGENTO_END = "# AGENTO:END"
CRONTAB_AFTER_SETUP = (
    "SHELL=/bin/bash\n"
    "PATH=/usr/bin\n"
    f"{AGENTO_BEGIN}\n"
    "\n"
    "# framework/logrotate\n"
    "0 0 * * * /opt/cron-agent/run.sh logrotate\n"
    "\n"
    f"{AGENTO_END}\n"
)


def test_skips_on_dry_run():
    with patch("agento.framework.db.get_connection") as mock_conn:
        RestoreCrontabOnSetupObserver().execute(FakeSetupCompleteEvent(dry_run=True))
        mock_conn.assert_not_called()


def test_restores_block_and_preserves_agento(caplog):
    rows = [
        {"issue_key": "AG-10", "summary": "Raport", "cron_expr": "0 8 * * *",
         "agent_view_code": ""},
    ]
    with caplog.at_level(logging.WARNING):
        written = _run_observer(rows, CRONTAB_AFTER_SETUP)

    assert written is not None
    # AGENTO block preserved …
    assert AGENTO_BEGIN in written
    assert "0 0 * * * /opt/cron-agent/run.sh logrotate" in written
    # … and JIRA-SYNC block restored with the entry and its reverse-mapped label.
    assert MARKER_BEGIN in written
    assert MARKER_END in written
    assert "# AG-10: Raport (Daily at 8:00)" in written
    assert "publish jira-cron AG-10" in written
    # Gap-recovery warning emitted (block was absent, schedule had entries).
    assert any("restored missing JIRA-SYNC" in r.message for r in caplog.records)


def test_agent_view_arg_included_for_scoped_schedule():
    rows = [
        {"issue_key": "AG-11", "summary": "View task", "cron_expr": "*/5 * * * *",
         "agent_view_code": "mieszko"},
    ]
    written = _run_observer(rows, CRONTAB_AFTER_SETUP)
    assert "publish jira-cron AG-11 --agent-view mieszko" in written
    assert "# AG-11: View task (Every 5min)" in written


def test_no_gap_warning_when_block_already_present(caplog):
    """Steady state: the block already matches → no rewrite, no gap warning."""
    existing = (
        CRONTAB_AFTER_SETUP
        + f"{MARKER_BEGIN}\n"
        + "\n"
        + "# AG-10: Raport (Daily at 8:00)\n"
        + "0 8 * * * set -a; source /opt/cron-agent/env; set +a; cd /workspace && "
          "/opt/cron-agent/run.sh publish jira-cron AG-10 "
          ">/dev/null 2>>/app/logs/cron-stderr.log\n"
        + "\n"
        + f"{MARKER_END}\n"
    )
    rows = [
        {"issue_key": "AG-10", "summary": "Raport", "cron_expr": "0 8 * * *",
         "agent_view_code": ""},
    ]
    with caplog.at_level(logging.WARNING):
        written = _run_observer(rows, existing)

    assert written is None  # unchanged → crontab - never invoked
    assert not any("restored missing" in r.message for r in caplog.records)


def test_empty_schedule_writes_no_block_and_no_warning(caplog):
    with caplog.at_level(logging.WARNING):
        written = _run_observer([], CRONTAB_AFTER_SETUP)
    # No entries and no pre-existing block → nothing to change.
    assert written is None
    assert not any("restored missing" in r.message for r in caplog.records)


def test_lock_held_is_skipped_without_write():
    from agento.framework.lock import LockHeld

    rows = [
        {"issue_key": "AG-10", "summary": "Raport", "cron_expr": "0 8 * * *",
         "agent_view_code": ""},
    ]
    cfg = MagicMock()
    cfg.frequency_map = FREQ_MAP

    lock_cm = MagicMock()
    lock_cm.return_value.__enter__.side_effect = LockHeld("held")

    with patch(
        "agento.modules.jira_periodic_tasks.src.crontab.subprocess.run"
    ) as mock_run, patch(
        "agento.framework.bootstrap.get_module_config", return_value=cfg
    ), patch(
        "agento.framework.database_config.DatabaseConfig.from_env"
    ), patch(
        "agento.framework.db.get_connection", return_value=_conn_returning(rows)
    ), patch(
        "agento.framework.lock.FileLock", lock_cm
    ):
        # get_current (for had_block) runs before the lock; the apply path must not.
        mock_run.return_value = MagicMock(returncode=0, stdout=CRONTAB_AFTER_SETUP)
        RestoreCrontabOnSetupObserver().execute(FakeSetupCompleteEvent(dry_run=False))
        assert ["crontab", "-"] not in [c.args[0] for c in mock_run.call_args_list]


def test_db_error_is_non_fatal():
    with patch(
        "agento.framework.bootstrap.get_module_config", return_value=MagicMock(frequency_map={})
    ), patch(
        "agento.framework.database_config.DatabaseConfig.from_env"
    ), patch(
        "agento.framework.db.get_connection", side_effect=Exception("db down")
    ):
        # Must not raise — setup:upgrade continues.
        RestoreCrontabOnSetupObserver().execute(FakeSetupCompleteEvent(dry_run=False))


def test_reverse_frequency_map_first_label_wins():
    m = _reverse_frequency_map({"Hourly": "0 * * * *", "Every 1h": "0 * * * *"})
    assert m["0 * * * *"] == "Hourly"


@pytest.mark.parametrize("empty", [None, {}])
def test_reverse_frequency_map_empty(empty):
    assert _reverse_frequency_map(empty or {}) == {}
