#!/bin/bash
set -e

# Agent configs are materialized per-agent_view by `workspace:build`. Credentials are
# selected again per run and written into the artifacts HOME. The consumer sets
# HOME=<artifacts_dir>, so container startup does not prepare config symlinks. The SSH
# private key is never a file at all — it goes config -> env -> a per-run ssh-agent
# (framework/ssh_prelude.py); only the non-secret .ssh files are written per run.

# Set timezone for cron daemon (reads /etc/localtime, not TZ)
if [ -n "$TZ" ] && [ -f "/usr/share/zoneinfo/$TZ" ]; then
    ln -sf "/usr/share/zoneinfo/$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
fi

# Ensure log directory and existing log files are writable by agent.
# Recursive chown heals stale UIDs from prior builds (e.g. when HOST_UID
# changed between releases) — without it the consumer crash-loops on
# `PermissionError: '/app/logs/consumer.log'` because pre-existing log
# files are still owned by the previous agent UID.
mkdir -p /app/logs
chown -R agent /app/logs 2>/dev/null || true

# Heal artifacts dir from pre-fix deployments where toolbox wrote files as root.
# Idempotent and metadata-only — fast even on large dirs. The `|| true` guards
# against partially-inaccessible mounts; if chown can't fix it here, the
# diagnostic in prepare_artifacts_dir will surface a clear error.
if [ -d /workspace/artifacts ]; then
    chown -R agent:agent /workspace/artifacts 2>/dev/null || true
fi

# No SSH identity may survive in a passwd home. `ssh` resolves ~/.ssh through getpwuid(),
# not $HOME, so /home/agent/.ssh and /root/.ssh are DEFAULT identity directories for every
# run: one run could plant an id_rsa there and a later run granted no key would silently
# use it. Runs as root, so this is the only place /root/.ssh can be dealt with — the spawn
# prelude runs as `agent` and cannot. FAIL CLOSED: a path we cannot clear is an active
# isolation break, not a warning.
for _d in /home/agent/.ssh /root/.ssh; do
    rm -rf "$_d" 2>/dev/null || true
    if [ -e "$_d" ] || [ -L "$_d" ]; then
        echo "agento: $_d exists and could not be removed - refusing to start" >&2
        exit 78
    fi
done

# A run's SSH identity is resolved PER RUN from that agent_view's config and delivered to
# one process. None of these names may arrive from the container environment: an ambient
# value would be inherited by every agent_view's runs, including views that were granted
# no key at all, which is exactly the cross-view use of one identity this release removes.
# `CONFIG__AGENT_VIEW__IDENTITY__SSH_PRIVATE_KEY` is refused for a second reason too: a
# CONFIG__* value entering the container environment is written to the store file below,
# which would put the key on disk. Set it in the DB
# (`bin/agento config:set agent_view/identity/ssh_private_key ... --scope agent_view`).
for _v in AGENTO_SSH_PRIVATE_KEY AGENTO_SSH_TTL SSH_AUTH_SOCK SSH_AGENT_PID \
          GIT_SSH_COMMAND CONFIG__AGENT_VIEW__IDENTITY__SSH_PRIVATE_KEY; do
    if [ -n "${!_v:-}" ]; then
        echo "agento: $_v is set in the container environment - refusing to start." >&2
        echo "agento: the SSH identity is per-run config, never an ambient variable." >&2
        exit 78
    fi
done

# Split the container environment in two. `setpriv` (the launcher) PRESERVES the
# environment, so the store is deliberately NOT in it: it lands in a root-only file that
# reaches a framework process on a file descriptor, and nowhere else. Both files are
# NUL-delimited — an environment value may legitimately contain a newline, and this is
# the file that carries credentials.
env -0 | PYTHONPATH=/opt/agento-src /opt/cron-agent/.venv/bin/python \
    /opt/cron-agent/split-env.py

# Root's crontab carries exactly one line: the renderer. It rebuilds the rest every minute
# from the installed module catalog and the `schedule` table — neither of which uid `agent`
# can write. Kept byte-identical to INSTALLER_LINE in install-crontab.py (guard test).
# The agent has no crontab at all.
crontab -u agent -r 2>/dev/null || true
cat <<'CRONTAB' | crontab -
# Generated by /entrypoint.sh. Do not edit manually.
SHELL=/bin/bash

* * * * * env -i PYTHONPATH=/opt/agento-src PATH=/usr/local/bin:/usr/bin:/bin /opt/cron-agent/.venv/bin/python /opt/cron-agent/install-crontab.py >/dev/null 2>>/app/logs/cron-stderr.log
CRONTAB

echo "Cron container started."

# Apply pending migrations, then render the crontab
SETUP_DONE=/tmp/.setup-done
rm -f "$SETUP_DONE"
echo "Running setup:upgrade..."
/opt/cron-agent/launch.sh --store -- /opt/cron-agent/run.sh setup:upgrade --skip-onboarding || {
    echo "setup:upgrade failed, exiting."
    exit 1
}
touch "$SETUP_DONE"

# Render the crontab now that migrations have run — a fresh database has no `schedule`
# table before this point. From here the root cron line keeps it current every minute.
env -i PYTHONPATH=/opt/agento-src PATH=/usr/local/bin:/usr/bin:/bin \
    /opt/cron-agent/.venv/bin/python /opt/cron-agent/install-crontab.py || \
    echo "install-crontab failed (cron jobs will retry in a minute)" >&2

echo "Crontab after setup:upgrade:"
crontab -l

# Start consumer as background process (runs as agent user)
echo "Starting consumer process..."
/opt/cron-agent/launch.sh --store -- /opt/cron-agent/run.sh consumer &
CONSUMER_PID=$!

# Propagate signals to consumer
trap "kill $CONSUMER_PID 2>/dev/null; wait $CONSUMER_PID 2>/dev/null; exit 0" SIGTERM SIGINT

# Start cron daemon in background
cron -f &
CRON_PID=$!

# Wait for either process to exit (fail-fast)
wait -n $CONSUMER_PID $CRON_PID
